### PR TITLE
Initial content commit

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Adds the framework described in ansible-collections/community.general#171, as well as the generic tests/units/plugins/modules/utils.py utility.

I'll adjust that PR to use this collection. Please don't merge until I got it working :)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
all

### CODE REVIEW

**Comment by felixfontein** [comment]
Ok, I have a commit for ansible-collections/community.general#171 which uses this collection: https://github.com/ansible-collections/community.general/commit/9b9a35030297a14013b89ebfd4c4cd27c2580819

When the collection is locally checked out, `ansible-test units --docker --python 3.7 -v tests/unit/plugins/modules/net_tools/test_hetzner_firewall*` runs through!

**Comment by gundalow** [comment]
Do we want CI here, or do we add that after we've got everything working?
I'm happy for you to merge when you are ready

**Comment by felixfontein** [comment]
@gundalow there's currently nothing that can be tested (well except sanity tests). I'm planning on adding a test module with a test unit test for it, but I'll only get to that on the weekend.

**Comment by felixfontein** [comment]
I manually ran sanity tests, and consequently updated the header of tests/unit/plugins/modules/utils.py. Should be ready for merging now.

**Comment by gundalow** [comment]
Thanks!

**Comment by felixfontein** [comment]
@gundalow thanks for creating the repo and merging this! :)

**Pull request merged**
